package:
  name: tesseract-robotics-superpack
  version: 0.5.0dev0

source:
  - git_url: https://github.com/ros-industrial/ros_industrial_cmake_boilerplate.git
    git_rev: 0.2.14
    folder: src/ros_industrial_cmake_boilerplate
  - git_url: https://github.com/Jmeyer1292/opw_kinematics.git
    folder: src/opw_kinematics
    git_rev: 0.4.4
    patches:
      - opw_interface_fix.patch
  - git_url: https://github.com/ethz-adrl/ifopt.git
    folder: src/ifopt
    git_rev: 40a6c8c14d1ab9789c342203d1fb3046eae07669
    patches:
      - ifopt_fix_win_find_ipopt.patch # [win]
      - ifopt_disable_build_tests.patch # [linux]
  - git_url: https://github.com/swri-robotics/descartes_light.git
    folder: src/descartes_light
    git_rev: 0.3.0
    patches:
      - descartes_cpp17.patch
  - git_url: https://github.com/tesseract-robotics/tesseract.git
    folder: src/tesseract
    git_rev: 0.8.3
    git_depth: 10
    patches:
      - tesseract_disable_examples.patch
  - git_url: https://github.com/tesseract-robotics/trajopt.git
    folder: src/trajopt
    git_rev: 0.2.2
    patches:
      - trajopt_fix.patch
  - git_url: https://github.com/tesseract-robotics/tesseract_planning.git
    folder: src/tesseract_planning
    git_rev: 0.9.3
    git_depth: 10
    patches:
      - tesseract_planning_fix.patch
  - git_url: https://github.com/tesseract-robotics/tesseract_python.git
    folder: src/tesseract_python
    git_rev: 43e77ece6386eed6e616db46661727f33fed88e9
    git_depth: 10
    patches:
      - tesseract_python_fix.patch
      - tesseract_python_win_fix.patch # [win]
  - git_url: https://github.com/bulletphysics/bullet3.git
    folder: src/bullet
    git_rev: "3.21"
    patches:
      - bullet3_fix.patch

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - pkg-config
    - swig
    - colcon-common-extensions 
    - lcov
    - {{ cdt('mesa-libgl-devel') }}    # [linux]
    - {{ cdt('mesa-dri-drivers') }}    # [linux]
  host:
    - boost-cpp 
    - eigen 
    - tinyxml2
    - console_bridge
    - assimp
    - urdfdom
    - fcl
    - octomap 
    - orocos-kdl 
    - pcl
    - gtest
    - gmock
    - pkg-config 
    - osqp 
    - osqp-eigen 
    - xz
    - ompl
    - flann
    - jsoncpp
    - taskflow 
    - python
    - numpy
    - pip
    - yaml-cpp
    - xorg-libx11    # [unix]
    - xorg-libxext   # [unix]
  run:
    - boost-cpp
    - eigen 
    - tinyxml2
    - console_bridge
    - assimp
    - urdfdom
    - fcl
    - octomap 
    - orocos-kdl 
    - pcl
    - gtest
    - gmock
    - osqp 
    - osqp-eigen 
    - xz
    - jsoncpp
    - ompl
    - taskflow 
    - python
    - numpy
    - yaml-cpp
    - xorg-libx11    # [unix]
    - xorg-libxext   # [unix]

test:
  files:
    - test_planning_server.py
  requires:
    - pytest

build:
  skip: true # [py<38]
  number: 1

about:
  home: https://github.com/ros-industrial-consortium/tesseract
  summary: Tesseract robotics motion planning framework


