{% set version = "0.6.0" %}
{% set ros_industrial_cmake_boilerplate_version = "0.3.0" %}
{% set opw_kinematics_version = "0.4.4" %}
{% set tesseract_version = "0.13.0" %}
{% set tesseract_planning_version = "0.12.0" %}
{% set trajopt_version = "0.3.0" %}
{% set descartes_light_version = "0.3.1" %}

package:
  name: tesseract-robotics-superpack
  version: {{ version }}

source:
  - git_url: https://github.com/ros-industrial/ros_industrial_cmake_boilerplate.git
    git_rev: {{ ros_industrial_cmake_boilerplate_version }}
    folder: src/ros_industrial_cmake_boilerplate
  - git_url: https://github.com/Jmeyer1292/opw_kinematics.git
    folder: src/opw_kinematics
    git_rev: {{ opw_kinematics_version }}
    patches:
      - opw_interface_fix.patch
  - git_url: https://github.com/swri-robotics/descartes_light.git
    folder: src/descartes_light
    git_rev: {{ descartes_light_version }}
  - git_url: https://github.com/johnwason/tesseract
    git_rev: pr/BulletLibsAbsPath
    folder: src/tesseract
  - git_url: https://github.com/tesseract-robotics/trajopt.git
    folder: src/trajopt
    git_rev: {{ trajopt_version }}
    patches:
      - trajopt_fix.patch
  - git_url: https://github.com/tesseract-robotics/tesseract_planning.git
    folder: src/tesseract_planning
    git_rev: 0c0983699f4afab3251daae6665bc0c9336f97f0
  - git_url: https://github.com/tesseract-robotics/tesseract_python.git
    folder: src/tesseract_python
    git_rev: d802447fa3e86f3aa1edf55fa919f348cbc2db90
    # patches:
    #   - tesseract_python_win_fix.patch # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - pkg-config
    - swig
    - colcon-common-extensions 
    - lcov
    - {{ cdt('mesa-libgl-devel') }}    # [linux]
    - {{ cdt('mesa-dri-drivers') }}    # [linux]
  host:
    - boost-cpp 
    - eigen 
    - tinyxml2
    - console_bridge
    - assimp
    - urdfdom
    - fcl
    - octomap 
    - orocos-kdl 
    - pcl
    - gtest
    - gmock
    - pkg-config 
    - osqp 
    - osqp-eigen 
    - xz
    - ompl
    - flann
    - jsoncpp
    - taskflow 
    - python
    - numpy
    - pip
    - yaml-cpp
    - bullet-cpp
    - xorg-libx11    # [unix]
    - xorg-libxext   # [unix]
  run:
    - boost-cpp
    - eigen 
    - tinyxml2
    - console_bridge
    - assimp
    - urdfdom
    - fcl
    - octomap 
    - orocos-kdl 
    - pcl
    - gtest
    - gmock
    - osqp 
    - osqp-eigen 
    - xz
    - jsoncpp
    - ompl
    - taskflow 
    - python
    - numpy
    - yaml-cpp
    - bullet-cpp
    - xorg-libx11    # [unix]
    - xorg-libxext   # [unix]

test:
  files:
    - test_planning_server.py
  requires:
    - pytest

build:
  skip: true # [py<38]
  number: 1

about:
  home: https://github.com/ros-industrial-consortium/tesseract
  summary: Tesseract robotics motion planning framework


