package:
  name: tesseract-robotics-superpack
  version: 0.3.0dev0

source:
  - git_url: https://github.com/ros-industrial/ros_industrial_cmake_boilerplate.git
    git_rev: 0.2.14
    folder: src/ros_industrial_cmake_boilerplate
  - git_url: https://github.com/Jmeyer1292/opw_kinematics.git
    folder: src/opw_kinematics
    git_rev: 0.4.4
  - git_url: https://github.com/ethz-adrl/ifopt.git
    folder: src/ifopt
    git_rev: 2.1.2
    patches:
      - ifopt_win_fix.patch # [win]
  - git_url: https://github.com/swri-robotics/descartes_light.git
    folder: src/descartes_light
    git_rev: 0.3.0
  - git_url: https://github.com/tesseract-robotics/tesseract.git
    folder: src/tesseract
    git_rev: 3a14e2a071a06c60763c0ea985de539fba7341b2
    patches:
      - tesseract_disable_examples.patch # [win]
    #   - tesseract_linux_fix.patch # [linux]
  - git_url: https://github.com/tesseract-robotics/trajopt.git
    folder: src/trajopt
    git_rev: 0.2.0
    patches:
      - trajopt_ros_win_fix.patch # [win]
      - trajopt_ros_linux_fix.patch # [linux]
  - git_url: https://github.com/tesseract-robotics/tesseract_planning.git
    folder: src/tesseract_planning
    git_rev: 1627231f3de8118f48d19272d0a7ac43dfe2f98a
    patches:
      - tesseract_planning_disable_examples.patch # [win]
    #   - tesseract_planning_linux_fix.patch # [linux]
  - git_url: https://github.com/tesseract-robotics/tesseract_python.git
    folder: src/tesseract_python
    git_rev: 43e77ece6386eed6e616db46661727f33fed88e9
  #   patches:
  #     - tesseract_python_win_fix.patch # [win]
  #     - tesseract_python_linux_fix.patch # [linux]


requirements:
  host:
    - boost-cpp 
    - colcon-common-extensions 
    - eigen 
    - tinyxml2
    - console_bridge
    - assimp
    - urdfdom 
    - bullet-cpp
    - fcl
    - octomap 
    - orocos-kdl 
    - pcl
    - gtest
    - gmock
    - pkg-config 
    - osqp 
    - osqp-eigen 
    - xz
    - ompl
    - flann
    - libode
    - jsoncpp
    - taskflow 
    - swig
    - python
    - numpy
    - pip
    - cmake
    - ninja # [win]
    - make # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - lcov # [linux]
  run:
    - boost-cpp
    - eigen 
    - tinyxml2
    - console_bridge
    - assimp
    - urdfdom 
    - bullet 
    - fcl
    - octomap 
    - orocos-kdl 
    - pcl
    - gtest
    - gmock
    - pkg-config 
    - osqp 
    - osqp-eigen 
    - xz
    - jsoncpp
    - ompl
    - libode
    - taskflow 
    - python
    - numpy

build:
  skip: true # [py<38]
  number: 0

about:
  home: https://github.com/ros-industrial-consortium/tesseract
  summary: Tesseract robotics motion planning framework


